export default function Step7TermsConditions() {
  return (
    <div className="bg-white rounded-lg shadow p-6 space-y-6">
      <div>
        <h2 className="text-xl font-semibold text-gray-900">Terms and Conditions</h2>
        <p className="text-sm text-gray-600 mt-1">
          Review the standard operating terms before proceeding to the final pricing output.
        </p>
      </div>

      <div className="rounded-lg border border-gray-200 bg-gray-50 p-5 space-y-4 text-sm text-gray-700">
        <p>
          Pricing outputs generated by this tool are intended for internal commercial review and planning purposes.
        </p>
        <p>
          Users are responsible for confirming the accuracy of inputs, validating business assumptions, and securing
          any internal approvals required before using pricing externally.
        </p>
        <p>
          Information entered into Elohi Pricing Calculator should be treated as confidential and proprietary.
        </p>
      </div>
    </div>
  )
}
